#!/bin/bash

# Don't have rvmsudo check for secure_path
export rvmsudo_secure_path=1

# This loads RVM into a shell session.
if [[ -s "$HOME/.rvm/scripts/rvm" ]]; then
  source "$HOME/.rvm/scripts/rvm"
  export PATH=$PATH:$HOME/.rvm/bin
fi

# replace irb with pry
if [[ $(which pry) ]]; then
  alias irb='SKIP_RAILS=true pry'
fi

alias bake='bundle exec rake'
alias rspec='bundle exec rspec'
