#!/bin/bash

VUNDLE_DIR=~/.vim/bundle/Vundle.vim

if [[ ! -d $VUNDLE_DIR ]]; then
   git clone https://github.com/gmarik/Vundle.vim.git $VUNDLE_DIR
   echo Remember to run :PluginInstall when first running vim
fi

