#!/bin/bash

export JAVA_HOME='/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home'
export CLICOLOR=1
export LSCOLORS=exfxcxdxbxegedabagacad

alias ls='ls -G'

# Set iTerm2 tab name
function tabname {
  echo -ne "\033]0;"$*"\007"
}

