#!/bin/bash

export EDITOR="/usr/bin/vim"
export GREP_OPTIONS='--color=auto'
export PAGER=less
export LESS='-iMSx2 -FXR'

# Set up bash history config
source $TOPIC_PATH/history.sh

# My favorite shell color scheme
source $TOPIC_PATH/base16-tomorrow.dark.sh

# So we get nice colors in man pages
# export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
# export LESS_TERMCAP_md=$(tput bold; tput setaf 6) # cyan
# export LESS_TERMCAP_me=$(tput sgr0)
# export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # yellow on blue
# export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
# export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) # white
# export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
# export LESS_TERMCAP_mr=$(tput rev)
# export LESS_TERMCAP_mh=$(tput dim)
# export LESS_TERMCAP_ZN=$(tput ssubm)
# export LESS_TERMCAP_ZV=$(tput rsubm)
# export LESS_TERMCAP_ZO=$(tput ssupm)
# export LESS_TERMCAP_ZW=$(tput rsupm)

# enable tab completion for sudo
complete -cf sudo

dottle_padd ~/.bin
dottle_padd /opt/local/bin
dottle_padd /opt/local/sbin
dottle_padd /usr/local/sbin
dottle_padd /usr/local/bin
dottle_padd ./bin
dottle_padd ./node_modules/bin

# vi editing mode
set -o vi

# Changing to projects real easy-like
if [[ -d ~/Projects ]]; then
  proj() {
    cd $(find ~/Projects -maxdepth 2 -type d -name "$1")
  }
  PROJECTS=$(find ~/Projects -maxdepth 2 -type d -exec basename {} \; | xargs)
  complete -W "$PROJECTS" proj
fi

3to2() {
  mv $1 .tmp.expand
  unexpand -t 3 .tmp.expand | expand -t 2 > $1
  rm -f .tmp.expand
}

# syntax highlighting less
hless() {
  source-highlight --out-format=esc --output=STDOUT -i $1 | less -R
}

function tmp {
  if [[ ! -d ~/.tmp ]]; then
    mkdir ~/.tmp
  fi
  cd ~/.tmp
}

function vimag {
  vim $(ag -l "$@")
}

function get_aws_info {
  if [[ -n "$AWS_PROFILE" ]]; then
    local output="<$AWS_PROFILE"
    if [[ -n "$AWS_REGION" ]]; then
      output="${output}:${AWS_REGION}"
    fi
    echo -n " ${output}>"
  fi
}

alias ll='ls -l'
alias ag='ag --color-path="0;34;40" --color-line-number="0;32;40"'
alias ww='ruby -rdate -e "puts Date.today.cweek"'
alias uuid="ruby -rsecurerandom -e 'puts SecureRandom.uuid.delete(\"-\")'"

export PS1='\[\033[1;37m\][\[\033[0m\]$(date +"%T")\[\033[1;37m\]]\[\033[0m\]\[\033[1;33m\]$(get_aws_info) \[\033[1;37m\]\w \[\033[0m\]'
