#!/bin/bash

export EDITOR="/usr/bin/vim"
export GREP_OPTIONS='--color=auto'
export PAGER=less
export LESS='-iMSx2 -FXR'

# My favorite shell color scheme
source $TOPIC_PATH/base16-tomorrow.dark.sh

# enable tab completion for sudo
complete -cf sudo

export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/bin:$PATH

# vi editing mode
set -o vi

# Changing to projects real easy-like
if [[ -d ~/Projects ]]; then
  proj() {
    cd $(find ~/Projects -maxdepth 2 -type d -name "$1")
  }
  PROJECTS=$(find ~/Projects -maxdepth 2 -type d -exec basename {} \; | xargs)
  complete -W "$PROJECTS" proj
fi

3to2() {
  mv $1 .tmp.expand
  unexpand -t 3 .tmp.expand | expand -t 2 > $1
  rm -f .tmp.expand
}

# syntax highlighting less
hless() {
  source-highlight --out-format=esc --output=STDOUT -i $1 | less -R
}

function tmp {
  if [[ ! -d ~/.tmp ]]; then
    mkdir ~/.tmp
  fi
  cd ~/.tmp
}

alias ag='ag --color-path="0;34;40" --color-line-number="0;32;40"'

export PS1='\[\033[1;37m\][\[\033[0m\]$(date +"%T")\[\033[1;37m\]]\[\033[0m\] \[\033[1;37m\]\w \[\033[0m\]'

