#!/bin/bash

if [[ `uname` == 'Darwin' ]]; then
  # MacOS
  font_dir="$HOME/Library/Fonts"
else
  # Linux
  font_dir="$HOME/.fonts"
  mkdir -p $font_dir
fi

# Copy all fonts to user fonts directory
find_command="find Meslo -name '*.[o,t]tf' -type f -print0"
eval $find_command | xargs -0 -I % cp % $font_dir/

# Reset font cache on Linux
if [[ -n `which fc-cache` ]]; then
  fc-cache -f $font_dir
fi

echo "* iTerm2 topic installed."
echo "* Don't forget to change the iTerm2 fonts (Regular and non-ASCII) to:"
echo "*   Meslo 14 LG M DZ"
echo "* Then load the iTerm2 color scheme:"
echo "*   $TOPIC_PATH/base16-tomorrow.dark.256.itermcolors"
